name: Publish to NPM
on:
  release:
    types: [published]
permissions:
  id-token: write

jobs:
  publish:
    environment: deploy
    runs-on: ubuntu-latest

    name: Publish
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: NPM Install
        run: npm ci

      - name: Publish (NPM)
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
