name: Testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Testing
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: NPM Install
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Typing
        run: npm run typescript

      - name: Testing
        run: npm run test --coverage

      - name: Prepare Build
        run: npm run build

      - name: Confirm Build Artifacts
        run: |
          if [ ! -d "lib/commonjs" ]; then echo "lib/commonjs is missing"; exit 1; fi
          if [ ! -d "lib/module" ]; then echo "lib/module is missing"; exit 1; fi
          if [ ! -d "lib/typescript" ]; then echo "lib/typescript is missing"; exit 1; fi
          echo "All build artifacts are present"
